name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up dotenv at root
        uses: jameslounds/create-dotenv@master
        with:
          directory: "."
          file-name: ".env"
          include-vars: '["AA", "BB", "CC", "TURBO_TOKEN"]'
        env:
          AA: "foobar"
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          BB: "foobar baz"
          CC: "thing\nthe\nother"
      - name: "show dotenv"
        run: "cat .env"
