name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup dotenv for playwright U value
        uses: iamsauravsharma/create-dotenv@v1.2.2
        with:
          env-prefix: "INCLUDE_"
        env:
          INCLUDE_AA: "foobar"
          INCLUDE_TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          INCLUDE_BB: "foobar baz"
          INCLUDE_CC: "\"thingtheother\""
      - name: "show dotenv"
        run: "cat .env"
      - run: "wc -l .env"
